### ISSUE TITLE
ModuleNotFoundError: No module named 'groq'

### ISSUE THREAD

**Issue by darkflare** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#2]
### ComfyUI Revision: 2139 [644a3ae5] | Released on '2024-04-20'
Traceback (most recent call last):
  File "X:\ComfyUI\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes\__init__.py", line 1, in <module>
    from .nodes.nodes import *
  File "X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes\nodes\nodes.py", line 13, in <module>
    from groq import Groq
ModuleNotFoundError: No module named 'groq'

Cannot import X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes module for custom nodes: No module named 'groq'

**Comment by MNeMoNiCuZ** [comment]
It appears that you need to install groq manually.
I'm not sure how ComfyUI installs requirements for nodes like this, but for this node to work you need to do:
`pip install groq` and `pip install configparser`.

**Comment by darkflare** [comment]
Created a requirements.txt under the node with:
```
groq
configparser

```
And it's running OK now 👌

**Comment by darkflare** [comment]
Created a requirements.txt under the node with:
```
groq
configparser

```
And it's running OK now 👌

**Comment by MNeMoNiCuZ** [comment]
Thanks for the PR. I'll try to figure out how to add it :D

I already have a requirements like this, but it looks like I put it in the wrong folder, oops!
